name: CICD Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job ${{github.job}} was automatically triggered by a ${{ github.event_name }} event."
  # Deploy-Build:
  #   runs-on: ubuntu-latest
  #   needs: Build
  #   steps:
  #     - run: echo "The job ${{github.job}} was started"
  # Test:
  #   runs-on: ubuntu-latest
  #   needs: [Build, Deploy-Build]
  #   steps:
  #     - run: echo "The job ${{github.job}} was started"
  Deploy-Dev:
    runs-on: ubuntu-latest
    needs: [Build]
    environment:
      name: Dev
    steps:
      - run: echo "The job ${{github.job}} was started"

  Deploy-Test:
    runs-on: ubuntu-latest
    needs: [Build]
    environment:
      name: Test
    steps:
      - run: echo "The job ${{github.job}} was started"

  Deploy-Prod:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions: write-all
    environment:
      name: Prod
    steps:
      - run: echo "The job ${{github.job}} was started"
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/myapp-${{github.run_number}}',
              sha: context.sha
            })
      - name: release
        uses: actions/create-release@v1
        id: create_release
        permissions: write-all
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: 'v${{github.run_number}}'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          - run: echo "The job ${{github.job}} Deployed in Prod"
