name: CICD Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  # Build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "🎉 The job ${{github.job}} was automatically triggered by a ${{ github.event_name }} event."
  # Deploy-Build:
  #   runs-on: ubuntu-latest
  #   needs: Build
  #   steps:
  #     - run: echo "The job ${{github.job}} was started"
  # Test:
  #   runs-on: ubuntu-latest
  #   needs: [Build, Deploy-Build]
  #   steps:
  #     - run: echo "The job ${{github.job}} was started"
  PrepareRelease:
    #needs: [Build, Deploy-Build, Test]
    runs-on: ubuntu-latest
    steps:
        - name: release
          uses: actions/create-release@v1
          id: create_release
          with:
            draft: false
            prerelease: false
            release_name: ${{ steps.version.outputs.version }}
            tag_name: ${{ github.ref }}
            body_path: CHANGELOG.md
          env:
            GITHUB_TOKEN: ${{ github.token }}
  Deploy-Dev:
    runs-on: ubuntu-latest
    needs: [PrepareRelease]
    environment:
      name: Dev
    steps:
      - run: echo "The job ${{github.job}} was started"
  Deploy-Test:
    runs-on: ubuntu-latest
    needs: [PrepareRelease]
    environment:
      name: Test
    steps:
      - run: echo "The job ${{github.job}} was started"
  Deploy-Prod:
    runs-on: ubuntu-latest
    needs: [PrepareRelease]
    environment:
      name: Prod
    steps:
      - run: echo "The job ${{github.job}} was started"
